# Generated by Django 5.0.1 on 2024-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_payment_accountno_alter_payment_cardname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
