# Generated by Django 5.0.1 on 2024-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_book_nos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='flight',
            name='rem',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
